### ISSUE TITLE
How to use this in a real ur robot?

### ISSUE THREAD

**Issue by WwYyFan** [neka-nat/ur_ws#1]
I am new to ROS,, if I want to run in a real ur robot,how can I start?

**Comment by neka-nat** [comment]
Hi, @WwYyFan.
This package simulates robotiq and ur5, but they can not run in real.
If you want to move only ur5 in real, you can run it with the following command.

```
roslaunch ur_bringup ur5_bringup.launch
```

**Comment by WwYyFan** [comment]
@neka-nat Hi , I have tried 
```
roslaunch ur_bringup ur5_bringup.launch
```
It can work , but the ur robot does not contain robotiq in rviz.

**Comment by neka-nat** [comment]
The above command is for UR 5 only.
In this package you can not work the real robotiq, please try to use the following package.
https://github.com/ros-industrial/robotiq
