### ISSUE TITLE
Multiple models

### ISSUE THREAD

**Issue by Geonhee-LEE** [neka-nat/ur_ws#3]
Hello,

Thanks to your contributions.

I want to run multiple ur5 using multi_ur_robotiq_gazebo.launch, but it break down including following error

 `Invalid roslaunch XML syntax: not well-formed (invalid token): line 13, column 3
The traceback for the exception was written to the log file
`

I thought % operation doesn't work in launch file. 
How about your env, it can be worked?

Regards

**Comment by neka-nat** [comment]
Hi @Geonhee-LEE ,

Thank you for reporting.
The launch file is erb file.
Please try the following command.

```
erb multi_ur_robotiq_gazebo.launch | roslaunch -
```

Thanks.
