### ISSUE TITLE
How to get the gazebo meshes?

### ISSUE THREAD

**Issue by nizhihao** [neka-nat/ur_ws#5]
![1](https://user-images.githubusercontent.com/32995094/91690214-2534e000-eb98-11ea-8170-3133f72d03b6.png)
Hello, first of all thanks for sharing your amazing job. I want to know How do you create above meshes and How can I get more meshes data such as Household goods,  daily necessities?
Thanks in advance ;)

**Comment by neka-nat** [comment]
Hi @nizhihao ,

Thanks you for the question.
I'm not sure where the original is.
Some of them is in the following repositories.
https://github.com/udacity/RoboND-Perception-Exercises/tree/master/Exercise-3/sensor_stick/models
